#!/usr/bin/perl -w

use strict;

unless(@ARGV >= 2){
    die "Usage: add_index <filename> <base> [header?]\n";
}

open(FILE, "<$ARGV[0]") || die "Failed to open file $ARGV[0]: $!\n";
chomp(my @file = <FILE>);
close(FILE);

my @newfile = ();

if(defined $ARGV[2]){
    push(@newfile, shift(@file));
}

my $index = $ARGV[1];

foreach my $line (@file){
    push(@newfile, "$line $index");
}

open(OUT, ">$ARGV[0].postfixed$ARGV[1]") || die "Failed to open file $ARGV[0].potsfixed$ARGV[1]\n";
foreach my $line (@newfile){
    print OUT $line . "\n";
}
