#!/usr/bin/perl -w

use strict;

unless(@ARGV == 2){
    die "Usage: avg_apd <amap> <dmap>\n";
}

my $amap_file = $ARGV[0];
my $dmap_file = $ARGV[1];

my @apds;

open(AMAP, "<$amap_file") || die "Failed to open $amap_file: $!\n";
chomp(my @amap = <AMAP>);
shift @amap; #throw away header
close(AMAP);

open(DMAP, "<$dmap_file") || die "Failed to open $dmap_file: $!\n";
chomp(my @dmap = <DMAP>);
shift @dmap; #throw away header
close(DMAP);

unless(@amap == @dmap){
    die "Map files didn't match!\n";
}

for(my $i = 0; $i < @amap; $i++){
    $apds[$i] = $dmap[$i] - $amap[$i];
    if($apds[$i] <= 0){
	pop(@apds);
    }
}

# Average our apds
my $sum = 0;

foreach my $node (@apds){
    $sum += $node;
}

my $average = ($sum/@apds);

print "$average\n";
