#!/usr/bin/perl -w

use strict;

unless(@ARGV == 1){
    die "Usage: edge2tri <.edgefile>\n";
}

open(EDGE, "<$ARGV[0]") || die "Failed to open file $ARGV[0]: $!\n";
chomp(my @edges = <EDGE>);
close(EDGE);

for(my $i = 0; $i < @edges; $i++){
    my @tmp = split(/\s+/, $edges[$i]);
    $tmp[2] = $tmp[1]; # duplicate last node to make it a triangle
    $edges[$i] = "$tmp[0] $tmp[1] $tmp[2]";
}

my @tmp = split(/\./, $ARGV[0]);

open(TRI, ">$tmp[0].tri") || die "Failed to open $tmp[0].tri: $!\n";
foreach my $line (@edges){
    print TRI "$line\n";
}
close(TRI);
