#!/usr/bin/perl -w

use strict;

unless(@ARGV == 2){
    die "Usage: procmod <pid> <max load avg>\n";
}

my $minion = $ARGV[0];
my $maxavg = $ARGV[1];

# Check that the process exists
kill 0 => $minion or die "Process $minion not found: $! \n";

# Check that the max load average is sane
unless($maxavg >= 0 && $maxavg <= 10){
    die "Please enter a reasonable load average!\n";
}

my $pid = fork;

if($pid){
    print "Going to daemon mode with pid $pid\n";
    exit 0;
}

kill STOP => $minion;

while(kill 0 => $minion){
    if(substr(`uptime`, -17, 4) < $maxavg){
	kill CONT => $minion;
    }else{
	kill STOP => $minion;
    }
    sleep 5;
}

print "Process $minion complete at `date`\n";



    


