#!/usr/bin/perl -w

use strict;

unless(@ARGV == 1){
    die "Usage: pts2node <2 .pts file>\n";
}

open(PTS, "<$ARGV[0]") || die "Failed to open file $ARGV[0]: $!\n";
chomp(my @pts = <PTS>);
close(PTS);

my @node = ();

$node[0] = $pts[0] . " 2 0 0";

for(my $i = 1; $i < @pts; $i++){
    my $linenum = $i-1;
    $node[$i] = "$linenum $pts[$i]";
}

my @filename = split(/\./, $ARGV[0]);

open(OUT, ">$filename[0].node") || die "Failed to open $filename[0].node: $!\n";
foreach my $line (@node){
    print OUT $line . "\n";
}
close(OUT);
