#!/usr/bin/perl -w

use strict;

sub usage {

  print <<__HERE
Takes a CARP mesh and removes all the regions with a specific ID.

Usage: $0 meshname region

__HERE
;

  die(@_) if @_;
}


my $points = [];

usage("Need to specify the meshname") if not @ARGV;

my $mesh = shift(@ARGV);

usage("Need to specify the region number") if not @ARGV;
my $region = shift(@ARGV);

open(ELEM, "$mesh.elem") or die("Can't open $mesh.elem for reading: $!\n");
my $temp = <ELEM>;
my $count = 0;
while (my $line = <ELEM>) {
  next if $line =~ /$region$/;
  $count++;
}
close(ELEM);


open(ELEM, "$mesh.elem") or die("Can't open $mesh.elem for reading: $!\n");
open(LON, "$mesh.lon") or die("Can't open $mesh.lon for reading: $!\n");
open(NEW_ELEM, ">removed.$mesh.elem") or die("Can't open removed.$mesh.elem for writing: $!\n");
open(NEW_LON, ">removed.$mesh.lon") or die("Can't open removed.$mesh.lon for writing: $!\n");
my $throw_away = <ELEM>;
print NEW_ELEM "$count\n";
while (my $line = <ELEM>) {
  my $lon_line = <LON>;
  next if $line =~ /$region$/;

  print NEW_ELEM $line;
  print NEW_LON $lon_line;

}
close(NEW_ELEM);
close(NEW_LON);
close(LON);
close(ELEM);
