#!/usr/bin/perl -w

use strict;

unless(@ARGV == 1){
    die "Usage: tri2tetras <.tri file>\n";
}

open(EDGE, "<$ARGV[0]") || die "Failed to open file $ARGV[0]: $!\n";
chomp(my @edges = <EDGE>);
close(EDGE);

for(my $i = 0; $i < @edges; $i++){
    my @tmp = split(/\s+/, $edges[$i]);
    $tmp[3] = $tmp[0]; # duplicate last node to make it a triangle
    $edges[$i] = "$tmp[0] $tmp[1] $tmp[2] $tmp[3] 1";
}

my @tmp = split(/\./, $ARGV[0]);

open(TRI, ">$tmp[0].tetras") || die "Failed to open $tmp[0].tetras: $!\n";
my $linect = @edges;

print TRI "$linect\n";

foreach my $line (@edges){
    print TRI "$line\n";
}

close(TRI);
