#!/usr/bin/perl -w

use strict;

# To be used for fixing extra linked-in files in AMAPs

unless(@ARGV == 1){
    die "Usage: trim [min number]\n";
}

my $deltime = $ARGV[0];

my @files = glob "*.t[0-9]*";
my @tmp = split(/\.t/,$files[0]);
my $prefix = $tmp[0];

print "Using file prefix: $prefix\n";

for(my $i = 0; $i < @files; $i++){
    my @temp = split(/\.t/,$files[$i]);
    $files[$i] = $temp[1];
}

foreach my $number (@files){
    if($number > $deltime){
	my $del_file = $prefix . ".t" . $number;
	unlink $del_file;
    } 
}

