#!/usr/bin/perl -w 

use strict;

#generates a file of $ARGV[0] lines of zeroes.

unless (@ARGV == 1 || @ARGV == 2){
    die "Usage: zerofile_gen <number of lines> [value]\n";
}

my $linect = $ARGV[0];
my $value = 0;

if(@ARGV == 2){
    $value = $ARGV[1];
}

open(ZERO, ">zerofile") || die "Failed to open zerofile: $!\n";

for(my $i = 0; $i < $linect; $i++){
    print ZERO "$value\n";
}

close(ZERO);
