#!/usr/bin/perl -w

use strict;

sub usage() {

  print <<__HERE

shift_t_files.pl increment <name>.t[0-9]*


Adds (increment) to the t files and moves them accordingly.

__HERE
;
  die;
}

usage() if (@ARGV < 2);

my $shift = shift @ARGV;

if ($shift+0 != $shift) {
  print "First argument must be amount to shift by.\n" ;
  usage();
}

my @shifted_files;
foreach my $file (@ARGV) {
  if (-e $file) {
    if ($file =~ m/(.*?)(\d+)/) {
      my $prefix = $1;
      my $index = $2;

      rename $file, $prefix.($index+$shift)."_new";
      push @shifted_files, $prefix.($index+$shift);
    }
  }
}

foreach my $file (@shifted_files) {
  rename "${file}_new", $file;
} 
